### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List         at io.prometheus.jmx.WebServer.main(WebServer.java:27)

### ISSUE THREAD

**Issue by lifeiqiang** [gentlezuo/jmx_exporter_multi#2]
进程信息
ps -ef|grep java
tomcat    35963      1  9 10:42 pts/1    00:00:51 /opt/jdk1.8.0_181/bin/java -Djava.util.logging.config.file=/app/tomcat/tomcat8_test_9080/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms2048m -Xmx2048m -XX:+UseConcMarkSweepGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -verbose:gc -Xloggc:/app/tomcat/tomcat8_test_9080/logs/gc_20210114.log -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0022 -Dcom.sun.management.jmxremote -Djava.rmi.server.hostname=10.18.3.222 -Dcom.sun.management.jmxremote.port=9990 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dignore.endorsed.dirs= -classpath /app/tomcat/tomcat8_test_9080/bin/bootstrap.jar:/app/tomcat/tomcat8_test_9080/bin/tomcat-juli.jar -Dcatalina.base=/app/tomcat/tomcat8_test_9080 -Dcatalina.home=/app/tomcat/tomcat8_test_9080 -Djava.io.tmpdir=/app/tomcat/tomcat8_test_9080/temp org.apache.catalina.startup.Bootstrap start
tomcat    36384  35821  0 10:52 pts/1    00:00:00 grep --color=auto java

执行报错信息
[tomcat@ara-dev006-10 ~]$ java -jar jmx_prometheus_httpserver_multi-0.1.0.jar 1 tomcat8_test_9080/bin/config.yaml 
Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List
        at io.prometheus.jmx.WebServer.main(WebServer.java:27)

**Comment by LljForge** [comment]
我也报这个错，解决了吗？
